-- Customer and KYC schema.
--
-- Identifying values are stored as AES-256-GCM ciphertext (the *_id / phone_number / email
-- columns) alongside a keyed HMAC "blind index" (*_index). The index makes exact-match search
-- and uniqueness possible without ever storing or scanning the plaintext.

CREATE TABLE customer (
    id                   CHAR(36)       NOT NULL,
    version              BIGINT         NOT NULL DEFAULT 0,
    tenant_id            CHAR(36)       NOT NULL,
    customer_number      VARCHAR(32)    NOT NULL,
    first_name           VARCHAR(80)    NOT NULL,
    middle_name          VARCHAR(80)    NULL,
    last_name            VARCHAR(80)    NOT NULL,
    date_of_birth        DATE           NOT NULL,
    gender               VARCHAR(24)    NULL,
    marital_status       VARCHAR(24)    NULL,
    id_type              VARCHAR(32)    NOT NULL,
    national_id          VARCHAR(512)   NOT NULL,
    national_id_index    CHAR(64)       NOT NULL,
    phone_number         VARCHAR(512)   NOT NULL,
    phone_index          CHAR(64)       NOT NULL,
    email                VARCHAR(512)   NULL,
    email_index          CHAR(64)       NULL,
    address_line1        VARCHAR(160)   NULL,
    address_line2        VARCHAR(160)   NULL,
    city                 VARCHAR(96)    NULL,
    state_province       VARCHAR(96)    NULL,
    postal_code          VARCHAR(24)    NULL,
    country_code         CHAR(2)        NULL,
    occupation           VARCHAR(96)    NULL,
    employer             VARCHAR(128)   NULL,
    monthly_income       DECIMAL(19, 4) NULL,
    branch_id            CHAR(36)       NULL,
    loan_officer_id      CHAR(36)       NULL,
    kyc_status           VARCHAR(24)    NOT NULL DEFAULT 'PENDING',
    kyc_verified_at      DATETIME(6)    NULL,
    kyc_verified_by      CHAR(36)       NULL,
    kyc_rejection_reason VARCHAR(512)   NULL,
    status               VARCHAR(24)    NOT NULL DEFAULT 'ACTIVE',
    deactivation_reason  VARCHAR(512)   NULL,
    created_at           DATETIME(6)    NOT NULL,
    created_by           VARCHAR(64)    NULL,
    updated_at           DATETIME(6)    NULL,
    updated_by           VARCHAR(64)    NULL,
    PRIMARY KEY (id),
    UNIQUE KEY ux_customer_tenant_number (tenant_id, customer_number),
    UNIQUE KEY ux_customer_tenant_national_id (tenant_id, national_id_index),
    KEY ix_customer_tenant_status (tenant_id, status),
    KEY ix_customer_tenant_kyc (tenant_id, kyc_status),
    KEY ix_customer_phone_index (phone_index),
    KEY ix_customer_name (tenant_id, last_name, first_name),
    KEY ix_customer_branch (tenant_id, branch_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE kyc_document (
    id                  CHAR(36)     NOT NULL,
    version             BIGINT       NOT NULL DEFAULT 0,
    tenant_id           CHAR(36)     NOT NULL,
    customer_id         CHAR(36)     NOT NULL,
    document_type       VARCHAR(32)  NOT NULL,
    document_number     VARCHAR(512) NULL,
    issuing_authority   VARCHAR(128) NULL,
    issued_on           DATE         NULL,
    expires_on          DATE         NULL,
    storage_key         VARCHAR(512) NOT NULL,
    content_type        VARCHAR(96)  NULL,
    file_size_bytes     BIGINT       NULL,
    checksum            CHAR(64)     NULL,
    verification_status VARCHAR(24)  NOT NULL DEFAULT 'PENDING',
    verified_by         CHAR(36)     NULL,
    verified_at         DATETIME(6)  NULL,
    rejection_reason    VARCHAR(512) NULL,
    created_at          DATETIME(6)  NOT NULL,
    created_by          VARCHAR(64)  NULL,
    updated_at          DATETIME(6)  NULL,
    updated_by          VARCHAR(64)  NULL,
    PRIMARY KEY (id),
    KEY ix_kyc_document_customer (tenant_id, customer_id),
    KEY ix_kyc_document_status (tenant_id, verification_status),
    CONSTRAINT fk_kyc_document_customer FOREIGN KEY (customer_id) REFERENCES customer (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
