-- Loan product configuration.
-- Money is DECIMAL(19,4), never FLOAT/DOUBLE: binary floating point cannot represent
-- 0.01 exactly and would drift over the life of a loan book.

CREATE TABLE loan_product (
    id                  CHAR(36)       NOT NULL,
    version             BIGINT         NOT NULL DEFAULT 0,
    tenant_id           CHAR(36)       NOT NULL,
    code                VARCHAR(32)    NOT NULL,
    name                VARCHAR(128)   NOT NULL,
    description         VARCHAR(512)   NULL,
    currency            CHAR(3)        NOT NULL,
    currency_scale      INT            NOT NULL DEFAULT 2,
    min_principal       DECIMAL(19, 4) NOT NULL,
    max_principal       DECIMAL(19, 4) NOT NULL,
    default_principal   DECIMAL(19, 4) NULL,
    min_annual_rate     DECIMAL(9, 4)  NOT NULL,
    max_annual_rate     DECIMAL(9, 4)  NOT NULL,
    default_annual_rate DECIMAL(9, 4)  NOT NULL,
    rate_quotation      VARCHAR(16)    NOT NULL DEFAULT 'ANNUAL',
    interest_method     VARCHAR(24)    NOT NULL,
    repayment_frequency VARCHAR(16)    NOT NULL,
    min_installments    INT            NOT NULL,
    max_installments    INT            NOT NULL,
    default_installments INT           NOT NULL,
    grace_type          VARCHAR(24)    NOT NULL DEFAULT 'NONE',
    max_grace_periods   INT            NOT NULL DEFAULT 0,
    fee_type            VARCHAR(24)    NOT NULL DEFAULT 'FLAT_AMOUNT',
    fee_value           DECIMAL(19, 4) NOT NULL DEFAULT 0,
    fee_collection      VARCHAR(32)    NOT NULL DEFAULT 'DEDUCT_FROM_DISBURSEMENT',
    day_count           VARCHAR(16)    NOT NULL DEFAULT 'ACTUAL_365',
    penalty_annual_rate DECIMAL(9, 4)  NOT NULL DEFAULT 0,
    penalty_basis       VARCHAR(32)    NOT NULL DEFAULT 'OVERDUE_TOTAL',
    penalty_grace_days  INT            NOT NULL DEFAULT 0,
    days_to_default     INT            NOT NULL DEFAULT 90,
    approval_levels     INT            NOT NULL DEFAULT 1,
    requires_collateral TINYINT(1)     NOT NULL DEFAULT 0,
    requires_guarantor  TINYINT(1)     NOT NULL DEFAULT 0,
    status              VARCHAR(16)    NOT NULL DEFAULT 'DRAFT',
    created_at          DATETIME(6)    NOT NULL,
    created_by          VARCHAR(64)    NULL,
    updated_at          DATETIME(6)    NULL,
    updated_by          VARCHAR(64)    NULL,
    PRIMARY KEY (id),
    UNIQUE KEY ux_loan_product_tenant_code (tenant_id, code),
    KEY ix_loan_product_tenant_status (tenant_id, status),
    CONSTRAINT ck_loan_product_principal_range CHECK (min_principal <= max_principal),
    CONSTRAINT ck_loan_product_rate_range CHECK (min_annual_rate <= max_annual_rate),
    CONSTRAINT ck_loan_product_term_range CHECK (min_installments <= max_installments)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
