-- Loan origination schema: applications and their immutable approval history.

CREATE TABLE loan_application (
    id                         CHAR(36)       NOT NULL,
    version                    BIGINT         NOT NULL DEFAULT 0,
    tenant_id                  CHAR(36)       NOT NULL,
    application_number         VARCHAR(32)    NOT NULL,
    customer_id                CHAR(36)       NOT NULL,
    customer_name              VARCHAR(160)   NULL,
    product_id                 CHAR(36)       NOT NULL,
    product_name               VARCHAR(128)   NULL,
    currency                   CHAR(3)        NOT NULL,
    requested_amount           DECIMAL(19, 4) NOT NULL,
    requested_installments     INT            NOT NULL,
    approved_amount            DECIMAL(19, 4) NULL,
    approved_installments      INT            NULL,
    annual_interest_rate       DECIMAL(9, 4)  NOT NULL,
    interest_method            VARCHAR(24)    NOT NULL,
    repayment_frequency        VARCHAR(16)    NOT NULL,
    grace_type                 VARCHAR(24)    NOT NULL DEFAULT 'NONE',
    grace_periods              INT            NOT NULL DEFAULT 0,
    purpose                    VARCHAR(512)   NULL,
    expected_disbursement_date DATE           NULL,
    first_repayment_date       DATE           NULL,
    status                     VARCHAR(24)    NOT NULL DEFAULT 'DRAFT',
    current_approval_level     INT            NOT NULL DEFAULT 0,
    required_approval_levels   INT            NOT NULL DEFAULT 1,
    branch_id                  CHAR(36)       NULL,
    loan_officer_id            CHAR(36)       NULL,
    submitted_at               DATETIME(6)    NULL,
    decided_at                 DATETIME(6)    NULL,
    rejection_reason           VARCHAR(512)   NULL,
    disbursed_at               DATETIME(6)    NULL,
    disbursement_date          DATE           NULL,
    disbursement_method        VARCHAR(32)    NULL,
    disbursement_reference     VARCHAR(64)    NULL,
    disbursed_amount           DECIMAL(19, 4) NULL,
    net_disbursed_amount       DECIMAL(19, 4) NULL,
    created_at                 DATETIME(6)    NOT NULL,
    created_by                 VARCHAR(64)    NULL,
    updated_at                 DATETIME(6)    NULL,
    updated_by                 VARCHAR(64)    NULL,
    PRIMARY KEY (id),
    UNIQUE KEY ux_application_tenant_number (tenant_id, application_number),
    KEY ix_application_tenant_status (tenant_id, status),
    KEY ix_application_customer (tenant_id, customer_id),
    KEY ix_application_branch (tenant_id, branch_id),
    CONSTRAINT ck_application_amount_positive CHECK (requested_amount > 0)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- Append-only: rows are inserted, never updated or deleted.
CREATE TABLE approval_record (
    id                    CHAR(36)       NOT NULL,
    version               BIGINT         NOT NULL DEFAULT 0,
    tenant_id             CHAR(36)       NOT NULL,
    application_id        CHAR(36)       NOT NULL,
    approval_level        INT            NOT NULL,
    decision              VARCHAR(24)    NOT NULL,
    decided_by            CHAR(36)       NULL,
    comment               VARCHAR(1024)  NULL,
    approved_amount       DECIMAL(19, 4) NULL,
    approved_installments INT            NULL,
    created_at            DATETIME(6)    NOT NULL,
    created_by            VARCHAR(64)    NULL,
    updated_at            DATETIME(6)    NULL,
    updated_by            VARCHAR(64)    NULL,
    PRIMARY KEY (id),
    KEY ix_approval_application (tenant_id, application_id),
    CONSTRAINT fk_approval_application FOREIGN KEY (application_id)
        REFERENCES loan_application (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
