-- Loan accounts, their repayment schedules, and the record of applied repayments.

CREATE TABLE loan_account (
    id                     CHAR(36)       NOT NULL,
    version                BIGINT         NOT NULL DEFAULT 0,
    tenant_id              CHAR(36)       NOT NULL,
    account_number         VARCHAR(32)    NOT NULL,
    application_id         CHAR(36)       NOT NULL,
    customer_id            CHAR(36)       NOT NULL,
    product_id             CHAR(36)       NOT NULL,
    currency               CHAR(3)        NOT NULL,
    currency_scale         INT            NOT NULL DEFAULT 2,
    principal              DECIMAL(19, 4) NOT NULL,
    total_interest         DECIMAL(19, 4) NOT NULL DEFAULT 0,
    total_fees             DECIMAL(19, 4) NOT NULL DEFAULT 0,
    total_repayable        DECIMAL(19, 4) NOT NULL DEFAULT 0,
    installment_amount     DECIMAL(19, 4) NOT NULL DEFAULT 0,
    annual_interest_rate   DECIMAL(9, 4)  NOT NULL,
    interest_method        VARCHAR(24)    NOT NULL,
    repayment_frequency    VARCHAR(16)    NOT NULL,
    number_of_installments INT            NOT NULL,
    outstanding_principal  DECIMAL(19, 4) NOT NULL DEFAULT 0,
    outstanding_interest   DECIMAL(19, 4) NOT NULL DEFAULT 0,
    outstanding_fees       DECIMAL(19, 4) NOT NULL DEFAULT 0,
    outstanding_penalty    DECIMAL(19, 4) NOT NULL DEFAULT 0,
    principal_paid         DECIMAL(19, 4) NOT NULL DEFAULT 0,
    interest_paid          DECIMAL(19, 4) NOT NULL DEFAULT 0,
    fees_paid              DECIMAL(19, 4) NOT NULL DEFAULT 0,
    penalty_paid           DECIMAL(19, 4) NOT NULL DEFAULT 0,
    advance_balance        DECIMAL(19, 4) NOT NULL DEFAULT 0,
    disbursement_date      DATE           NOT NULL,
    first_repayment_date   DATE           NOT NULL,
    maturity_date          DATE           NOT NULL,
    last_payment_date      DATE           NULL,
    days_past_due          INT            NOT NULL DEFAULT 0,
    overdue_amount         DECIMAL(19, 4) NOT NULL DEFAULT 0,
    status                 VARCHAR(24)    NOT NULL DEFAULT 'ACTIVE',
    closed_on              DATE           NULL,
    branch_id              CHAR(36)       NULL,
    loan_officer_id        CHAR(36)       NULL,
    created_at             DATETIME(6)    NOT NULL,
    created_by             VARCHAR(64)    NULL,
    updated_at             DATETIME(6)    NULL,
    updated_by             VARCHAR(64)    NULL,
    PRIMARY KEY (id),
    UNIQUE KEY ux_loan_account_tenant_number (tenant_id, account_number),
    -- One account per application: this is what makes disbursement-event consumption idempotent.
    UNIQUE KEY ux_loan_account_application (tenant_id, application_id),
    KEY ix_loan_account_customer (tenant_id, customer_id),
    KEY ix_loan_account_status (tenant_id, status),
    KEY ix_loan_account_arrears (tenant_id, days_past_due),
    CONSTRAINT ck_loan_account_balances_non_negative CHECK (
        outstanding_principal >= 0 AND outstanding_interest >= 0
        AND outstanding_fees >= 0 AND outstanding_penalty >= 0)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE schedule_installment (
    id                 CHAR(36)       NOT NULL,
    version            BIGINT         NOT NULL DEFAULT 0,
    tenant_id          CHAR(36)       NOT NULL,
    loan_account_id    CHAR(36)       NOT NULL,
    installment_number INT            NOT NULL,
    due_date           DATE           NOT NULL,
    opening_balance    DECIMAL(19, 4) NOT NULL DEFAULT 0,
    principal_due      DECIMAL(19, 4) NOT NULL DEFAULT 0,
    interest_due       DECIMAL(19, 4) NOT NULL DEFAULT 0,
    fee_due            DECIMAL(19, 4) NOT NULL DEFAULT 0,
    penalty_due        DECIMAL(19, 4) NOT NULL DEFAULT 0,
    principal_paid     DECIMAL(19, 4) NOT NULL DEFAULT 0,
    interest_paid      DECIMAL(19, 4) NOT NULL DEFAULT 0,
    fee_paid           DECIMAL(19, 4) NOT NULL DEFAULT 0,
    penalty_paid       DECIMAL(19, 4) NOT NULL DEFAULT 0,
    closing_balance    DECIMAL(19, 4) NOT NULL DEFAULT 0,
    grace_installment  TINYINT(1)     NOT NULL DEFAULT 0,
    status             VARCHAR(24)    NOT NULL DEFAULT 'PENDING',
    settled_on         DATE           NULL,
    created_at         DATETIME(6)    NOT NULL,
    created_by         VARCHAR(64)    NULL,
    updated_at         DATETIME(6)    NULL,
    updated_by         VARCHAR(64)    NULL,
    PRIMARY KEY (id),
    UNIQUE KEY ux_installment_account_number (loan_account_id, installment_number),
    KEY ix_installment_account (tenant_id, loan_account_id),
    KEY ix_installment_due (tenant_id, due_date, status),
    CONSTRAINT fk_installment_account FOREIGN KEY (loan_account_id)
        REFERENCES loan_account (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- Makes repayment posting idempotent and preserves the original split so a reversal can be
-- replayed exactly rather than recomputed against balances that have since moved.
CREATE TABLE applied_repayment (
    id                  CHAR(36)       NOT NULL,
    version             BIGINT         NOT NULL DEFAULT 0,
    tenant_id           CHAR(36)       NOT NULL,
    loan_account_id     CHAR(36)       NOT NULL,
    payment_id          CHAR(36)       NOT NULL,
    amount              DECIMAL(19, 4) NOT NULL,
    principal_allocated DECIMAL(19, 4) NOT NULL DEFAULT 0,
    interest_allocated  DECIMAL(19, 4) NOT NULL DEFAULT 0,
    fee_allocated       DECIMAL(19, 4) NOT NULL DEFAULT 0,
    penalty_allocated   DECIMAL(19, 4) NOT NULL DEFAULT 0,
    excess_amount       DECIMAL(19, 4) NOT NULL DEFAULT 0,
    value_date          DATE           NOT NULL,
    reversed_at         DATETIME(6)    NULL,
    reversed_by         CHAR(36)       NULL,
    reversal_reason     VARCHAR(512)   NULL,
    created_at          DATETIME(6)    NOT NULL,
    created_by          VARCHAR(64)    NULL,
    updated_at          DATETIME(6)    NULL,
    updated_by          VARCHAR(64)    NULL,
    PRIMARY KEY (id),
    UNIQUE KEY ux_applied_repayment_payment (tenant_id, payment_id),
    KEY ix_applied_repayment_account (tenant_id, loan_account_id),
    CONSTRAINT fk_applied_repayment_account FOREIGN KEY (loan_account_id)
        REFERENCES loan_account (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
